### PR TITLE
Create benchmark.py

### PR DESCRIPTION
**Pull request by noorains**

### CODE REVIEW

**Review by kvelleby — COMMENTED** [review]
Hi! As I understand this code, the bootstrap selects num_samples random values from the pool of fatalities observations for the 3-15 month period. Similarly, the "hist" just take the last 3-15 months values as the values for the next 1-12 months, and poisson transform this. 

I think what we would want for this "hist" is just the last observed value (i.e. the df.month_id.min() - month_lag), then a poisson distribution over that, copied for each month in the test period. 

I think also we should allow for varying test periods, defined as a date-interval or something like that. (E.g., allow for a test interval starting in June 2020 and ending in December 2020) However, that can wait after we get the utilities.py and this into main.

**Comment by kvelleby** [comment]
Does this run with main() on top?

**Comment by noorains** [comment]
> Does this run with main() on top?

yeah, it does here. 👍

**Review by kvelleby — APPROVED** [review]
Looks good to me.

**Pull request merged**
